apiVersion: v1
kind: Pod
metadata:
  name: ${podName}
spec:
  restartPolicy: Never
  containers:
    - name: ${containerName}
      image: ${imageName}
      command: ["/bin/bash", "-c", "bash /app/systemData/script/run.sh"]
      ports:
        - containerPort: 80
      volumeMounts:
        - name: model-data
          mountPath: /app/${userData}/modelData
        - name: evaluation-data
          mountPath: /app/${userData}/${evaluationData}/${evaluationType}
        - name: system-data
          mountPath: /app/systemData
      env:
        - name: containerName
          value: ${containerName}
        - name: namespace
          value: default
  volumes:
    - name: model-data
      nfs:
        server: ${nfsIP}
        path: ${rootPath}/${userData}/${userId}/${modelId}/modelData
        readOnly: false
    - name: evaluation-data
      nfs:
        server: ${nfsIP}
        path: ${rootPath}/${userData}/${userId}/${modelId}/${evaluationData}/${evaluationType}
        readOnly: false
    - name: system-data
      nfs:
        server: ${nfsIP}
        path: ${rootPath}/${systemData}
        readOnly: false